import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';

import {
  MedicalCode,
  Insurance,
  InsuranceVerification,
  Billing,
  BillingLineItem,
  InsuranceClaim,
  Payment,
  ClaimDenial,
  ClaimAppeal,
  RevenueReport,
  Remittance,
  BillingDispute,
  SubscriptionPlan,
  PatientSubscription,
} from './entities';

import {
  MedicalCodeService,
  InsuranceService,
  BillingService,
  ClaimService,
  PaymentService,
  DenialService,
  ReportService,
  InvoicePdfService,
  RemittanceService,
  DisputeService,
  SubscriptionService,
} from './services';

import {
  MedicalCodeController,
  InsuranceController,
  BillingController,
  ClaimController,
  PaymentController,
  DenialController,
  AppealController,
  ReportController,
  RemittanceController,
  DisputeController,
  SubscriptionController,
} from './controllers';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      MedicalCode,
      Insurance,
      InsuranceVerification,
      Billing,
      BillingLineItem,
      InsuranceClaim,
      Payment,
      ClaimDenial,
      ClaimAppeal,
      RevenueReport,
      Remittance,
      BillingDispute,
      SubscriptionPlan,
      PatientSubscription,
    ]),
  ],
  controllers: [
    MedicalCodeController,
    InsuranceController,
    BillingController,
    ClaimController,
    PaymentController,
    DenialController,
    AppealController,
    ReportController,
    RemittanceController,
    DisputeController,
    SubscriptionController,
  ],
  providers: [
    MedicalCodeService,
    InsuranceService,
    BillingService,
    ClaimService,
    PaymentService,
    DenialService,
    ReportService,
    InvoicePdfService,
    RemittanceService,
    DisputeService,
    SubscriptionService,
  ],
  exports: [
    MedicalCodeService,
    InsuranceService,
    BillingService,
    ClaimService,
    PaymentService,
    DenialService,
    ReportService,
    InvoicePdfService,
    RemittanceService,
    DisputeService,
    SubscriptionService,
  ],
})
export class BillingModule {}
